import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
import CommonLayout from "@/Components/Layout/CommonLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Interior Design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en" data-theme="light">
        <body className={inter.className}>
          <CommonLayout> {children}</CommonLayout>
        </body>
      </html>
    </Providers>
  );
}
